/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Insert the given text at the current cursor position.
 *
 * The whole text string is entered at once so it is performed quickly.
 *
 * ##### Arguments
 * * `text` - Text to be inserted
 */
export function insertText(text: string): void
